#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: kuroro2121
 * Date: 14/10/21
 * Time: 16:30
 */

use Doctrine\Common\Annotations\AnnotationRegistry;

$loader = (require_once __DIR__ . '/autoload.php');
require_once __DIR__ . '/../../app/AppKernel.php';

AnnotationRegistry::registerLoader(
    array(
        $loader,
        'loadClass'
    )
);

/**
 * Test code
 * Greg: I will put these code into commands
 */


/*$apt = new \AutoMaid\AutoMaid();
$apt->init();
$ret = $apt->loadFiles(__DIR__ . '/../../src');
$apt->parseServices();
$apt->writeServiceConfiguration();*/


