<?php
/**
 * Created by PhpStorm.
 * User: kuroro2121
 * Date: 14/10/24
 * Time: 19:04
 */
namespace AutoMaid\Command;

use AutoMaid\DirTrait;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ConfigurationInit extends Command
{
    use DirTrait;

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->detectProjectDir();

        // Step 1. handle other services.yml files
        $files = preg_split('/[ \n]+/', shell_exec(
            'find ' . $this->projectDir . '/src -name "services.yml" '
        ));

        // Step 2. handle app/config/config.yml
        $files[] = $this->projectDir . '/app/config/config.yml';  // TODO make this configurable later

        foreach ($files as $file) {
            if (file_exists($file)) {
                shell_exec(
                    __DIR__ . '/../../../bin/handle_imports.sh ' . trim($file)
                );
            } else {
                // WARNING, very rare case
            }
        }
    }

    public function getDescription()
    {
        return "Add imports to services configuration files";
    }
}