<?php
/**
 * Created by PhpStorm.
 * User: kuroro2121
 * Date: 14/10/31
 * Time: 22:55
 */

namespace AutoMaid\Command;


use Symfony\Component\Console\Command\Command;

class ConfigurationRefactor extends Command{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function getDescription()
    {
        return parent::getDescription(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
} 