<?php
/**
 * Created by PhpStorm.
 * User: kuroro2121
 * Date: 14/10/31
 * Time: 22:10
 */

namespace AutoMaid\Command;


use AutoMaid\DirTrait;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ConfigurationClean extends Command
{
    use DirTrait;

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->detectProjectDir();
        $files = preg_split(
            '/[ \n]+/',
            shell_exec(
                'find ' . $this->projectDir . '/src' . ' -name "am_services.yml"'
            )
        );

        $files[] = $this->projectDir . '/app/config/am_services.yml';

        foreach ($files as $file) {
            if (file_exists($file)) {
                rename($file, $file . '.' . date("D_M_d_Y_G:i") . '.bak');
            }
        }
    }

    public function getDescription()
    {
        return 'Remove all am_services.yml generated.';
    }


} 