<?php
/**
 * Created by PhpStorm.
 * User: kuroro2121
 * Date: 14/10/24
 * Time: 19:04
 */
namespace AutoMaid\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ConfigurationInit extends Command {
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $projectDir = dirname(dirname(dirname(dirname(dirname(dirname((__DIR__)))))));
        // Step 1. handle app/config/config.yml
        $path = $projectDir . '/app/config/config.yml';  // TODO make this configurable later
        if (file_exists($path)) {
            shell_exec(__DIR__ . '/../../../bin/handle_imports.sh ' . $path);
        }

        // Step 2. handle other services.yml files
        $files = shell_exec('find ' . $projectDir . '/src -name "services.yml" ');
        foreach (preg_split('/ +/', $files) as $file) {
            shell_exec(__DIR__ . '/../../../bin/handle_imports.sh ' . trim($file));
        }
    }

    public function getDescription()
    {
        return "Add imports to services configuration files";
    }
}