<?php
/**
 * Created by PhpStorm.
 * User: kuroro2121
 * Date: 14/10/24
 * Time: 19:06
 */

namespace AutoMaid\Command;


use AutoMaid\AutoMaid;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ConfigurationGen extends Command {

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $automaid = new AutoMaid();
        $automaid->init();
        $projectDir = dirname(dirname(dirname(dirname(dirname(__DIR__)))));
        $projectSrc = $projectDir . '/src';
        $automaid->loadFiles($projectSrc);
        $automaid->getServices();
        $automaid->parseServices();

        $automaid->writeServiceConfiguration();
    }

    public function getDescription()
    {
        return 'Generate service configuration based on annotations';
    }
}